// Code generated by 'yaegi extract go-hep.org/x/hep/hbook'. DO NOT EDIT.

package symbols

import (
	"go/constant"
	"go/token"
	"reflect"

	"go-hep.org/x/hep/hbook"
)

func init() {
	Symbols["go-hep.org/x/hep/hbook/hbook"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddH1D":           reflect.ValueOf(hbook.AddH1D),
		"AddH2D":           reflect.ValueOf(hbook.AddH2D),
		"AddH3D":           reflect.ValueOf(hbook.AddH3D),
		"AddScaledH1D":     reflect.ValueOf(hbook.AddScaledH1D),
		"AddScaledH2D":     reflect.ValueOf(hbook.AddScaledH2D),
		"AddScaledH3D":     reflect.ValueOf(hbook.AddScaledH3D),
		"AgrestiCoull":     reflect.ValueOf(hbook.AgrestiCoull),
		"BinomialInterval": reflect.ValueOf(hbook.BinomialInterval),
		"BngE":             reflect.ValueOf(hbook.BngE),
		"BngN":             reflect.ValueOf(hbook.BngN),
		"BngNE":            reflect.ValueOf(hbook.BngNE),
		"BngNW":            reflect.ValueOf(hbook.BngNW),
		"BngS":             reflect.ValueOf(hbook.BngS),
		"BngSE":            reflect.ValueOf(hbook.BngSE),
		"BngSW":            reflect.ValueOf(hbook.BngSW),
		"BngW":             reflect.ValueOf(hbook.BngW),
		"ClopperPearson":   reflect.ValueOf(hbook.ClopperPearson),
		"DefaultEffLevel":  reflect.ValueOf(constant.MakeFromLiteral("0.682689492137085999980301853629072184048709459602832794189453125", token.FLOAT, 0)),
		"DivIgnoreNaNs":    reflect.ValueOf(hbook.DivIgnoreNaNs),
		"DivReplaceNaNs":   reflect.ValueOf(hbook.DivReplaceNaNs),
		"DivideH1D":        reflect.ValueOf(hbook.DivideH1D),
		"NewEfficiency":    reflect.ValueOf(hbook.NewEfficiency),
		"NewH1D":           reflect.ValueOf(hbook.NewH1D),
		"NewH1DFromBins":   reflect.ValueOf(hbook.NewH1DFromBins),
		"NewH1DFromEdges":  reflect.ValueOf(hbook.NewH1DFromEdges),
		"NewH2D":           reflect.ValueOf(hbook.NewH2D),
		"NewH2DFromEdges":  reflect.ValueOf(hbook.NewH2DFromEdges),
		"NewH3D":           reflect.ValueOf(hbook.NewH3D),
		"NewH3DFromEdges":  reflect.ValueOf(hbook.NewH3DFromEdges),
		"NewP1D":           reflect.ValueOf(hbook.NewP1D),
		"NewP1DFromH1D":    reflect.ValueOf(hbook.NewP1DFromH1D),
		"NewRand1D":        reflect.ValueOf(hbook.NewRand1D),
		"NewS2D":           reflect.ValueOf(hbook.NewS2D),
		"NewS2DFrom":       reflect.ValueOf(hbook.NewS2DFrom),
		"NewS2DFromH1D":    reflect.ValueOf(hbook.NewS2DFromH1D),
		"NewS2DFromP1D":    reflect.ValueOf(hbook.NewS2DFromP1D),
		"Normal":           reflect.ValueOf(hbook.Normal),
		"NumOutflows3D":    reflect.ValueOf(constant.MakeFromLiteral("26", token.INT, 0)),
		"Outflow2D":        reflect.ValueOf(hbook.Outflow2D),
		"Outflow3D":        reflect.ValueOf(hbook.Outflow3D),
		"OverflowBin1D":    reflect.ValueOf(constant.MakeFromLiteral("-2", token.INT, 0)),
		"SubH1D":           reflect.ValueOf(hbook.SubH1D),
		"SubH2D":           reflect.ValueOf(hbook.SubH2D),
		"SubH3D":           reflect.ValueOf(hbook.SubH3D),
		"UnderflowBin1D":   reflect.ValueOf(constant.MakeFromLiteral("-1", token.INT, 0)),
		"Wilson":           reflect.ValueOf(hbook.Wilson),
		"WithEffInterval":  reflect.ValueOf(hbook.WithEffInterval),
		"WithEffLevel":     reflect.ValueOf(hbook.WithEffLevel),

		// type definitions
		"Annotation":   reflect.ValueOf((*hbook.Annotation)(nil)),
		"Bin":          reflect.ValueOf((*hbook.Bin)(nil)),
		"Bin1D":        reflect.ValueOf((*hbook.Bin1D)(nil)),
		"Bin1Ds":       reflect.ValueOf((*hbook.Bin1Ds)(nil)),
		"Bin2D":        reflect.ValueOf((*hbook.Bin2D)(nil)),
		"Bin3D":        reflect.ValueOf((*hbook.Bin3D)(nil)),
		"BinP1D":       reflect.ValueOf((*hbook.BinP1D)(nil)),
		"Binning1D":    reflect.ValueOf((*hbook.Binning1D)(nil)),
		"Binning2D":    reflect.ValueOf((*hbook.Binning2D)(nil)),
		"Binning3D":    reflect.ValueOf((*hbook.Binning3D)(nil)),
		"Count":        reflect.ValueOf((*hbook.Count)(nil)),
		"Dist0D":       reflect.ValueOf((*hbook.Dist0D)(nil)),
		"Dist1D":       reflect.ValueOf((*hbook.Dist1D)(nil)),
		"Dist2D":       reflect.ValueOf((*hbook.Dist2D)(nil)),
		"Dist3D":       reflect.ValueOf((*hbook.Dist3D)(nil)),
		"DivOptions":   reflect.ValueOf((*hbook.DivOptions)(nil)),
		"EffBin":       reflect.ValueOf((*hbook.EffBin)(nil)),
		"EffOption":    reflect.ValueOf((*hbook.EffOption)(nil)),
		"Efficiency":   reflect.ValueOf((*hbook.Efficiency)(nil)),
		"H1D":          reflect.ValueOf((*hbook.H1D)(nil)),
		"H2D":          reflect.ValueOf((*hbook.H2D)(nil)),
		"H3D":          reflect.ValueOf((*hbook.H3D)(nil)),
		"Histogram":    reflect.ValueOf((*hbook.Histogram)(nil)),
		"IntervalKind": reflect.ValueOf((*hbook.IntervalKind)(nil)),
		"Object":       reflect.ValueOf((*hbook.Object)(nil)),
		"P1D":          reflect.ValueOf((*hbook.P1D)(nil)),
		"Point2D":      reflect.ValueOf((*hbook.Point2D)(nil)),
		"Rand1D":       reflect.ValueOf((*hbook.Rand1D)(nil)),
		"Range":        reflect.ValueOf((*hbook.Range)(nil)),
		"S2D":          reflect.ValueOf((*hbook.S2D)(nil)),
		"S2DOpts":      reflect.ValueOf((*hbook.S2DOpts)(nil)),

		// interface wrapper definitions
		"_Bin":       reflect.ValueOf((*_go_hep_org_x_hep_hbook_Bin)(nil)),
		"_Histogram": reflect.ValueOf((*_go_hep_org_x_hep_hbook_Histogram)(nil)),
		"_Object":    reflect.ValueOf((*_go_hep_org_x_hep_hbook_Object)(nil)),
	}
}

// _go_hep_org_x_hep_hbook_Bin is an interface wrapper for Bin type
type _go_hep_org_x_hep_hbook_Bin struct {
	IValue      interface{}
	WEffEntries func() float64
	WEntries    func() int64
	WRank       func() int
	WSumW       func() float64
	WSumW2      func() float64
}

func (W _go_hep_org_x_hep_hbook_Bin) EffEntries() float64 {
	return W.WEffEntries()
}
func (W _go_hep_org_x_hep_hbook_Bin) Entries() int64 {
	return W.WEntries()
}
func (W _go_hep_org_x_hep_hbook_Bin) Rank() int {
	return W.WRank()
}
func (W _go_hep_org_x_hep_hbook_Bin) SumW() float64 {
	return W.WSumW()
}
func (W _go_hep_org_x_hep_hbook_Bin) SumW2() float64 {
	return W.WSumW2()
}

// _go_hep_org_x_hep_hbook_Histogram is an interface wrapper for Histogram type
type _go_hep_org_x_hep_hbook_Histogram struct {
	IValue      interface{}
	WAnnotation func() hbook.Annotation
	WEntries    func() int64
	WName       func() string
	WRank       func() int
}

func (W _go_hep_org_x_hep_hbook_Histogram) Annotation() hbook.Annotation {
	return W.WAnnotation()
}
func (W _go_hep_org_x_hep_hbook_Histogram) Entries() int64 {
	return W.WEntries()
}
func (W _go_hep_org_x_hep_hbook_Histogram) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_hbook_Histogram) Rank() int {
	return W.WRank()
}

// _go_hep_org_x_hep_hbook_Object is an interface wrapper for Object type
type _go_hep_org_x_hep_hbook_Object struct {
	IValue      interface{}
	WAnnotation func() hbook.Annotation
	WName       func() string
}

func (W _go_hep_org_x_hep_hbook_Object) Annotation() hbook.Annotation {
	return W.WAnnotation()
}
func (W _go_hep_org_x_hep_hbook_Object) Name() string {
	return W.WName()
}
