// Code generated by 'yaegi extract go-hep.org/x/hep/groot'. DO NOT EDIT.

package symbols

import (
	"go/constant"
	"go/token"
	"reflect"

	"go-hep.org/x/hep/groot"
)

func init() {
	Symbols["go-hep.org/x/hep/groot/groot"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Create":    reflect.ValueOf(groot.Create),
		"NewReader": reflect.ValueOf(groot.NewReader),
		"Open":      reflect.ValueOf(groot.Open),
		"Version":   reflect.ValueOf(constant.MakeFromLiteral("64000", token.INT, 0)),

		// type definitions
		"Array":         reflect.ValueOf((*groot.Array)(nil)),
		"Collection":    reflect.ValueOf((*groot.Collection)(nil)),
		"File":          reflect.ValueOf((*groot.File)(nil)),
		"FileOption":    reflect.ValueOf((*groot.FileOption)(nil)),
		"List":          reflect.ValueOf((*groot.List)(nil)),
		"Named":         reflect.ValueOf((*groot.Named)(nil)),
		"ObjArray":      reflect.ValueOf((*groot.ObjArray)(nil)),
		"ObjString":     reflect.ValueOf((*groot.ObjString)(nil)),
		"Object":        reflect.ValueOf((*groot.Object)(nil)),
		"Reader":        reflect.ValueOf((*groot.Reader)(nil)),
		"SeqCollection": reflect.ValueOf((*groot.SeqCollection)(nil)),

		// interface wrapper definitions
		"_Array":         reflect.ValueOf((*_go_hep_org_x_hep_groot_Array)(nil)),
		"_Collection":    reflect.ValueOf((*_go_hep_org_x_hep_groot_Collection)(nil)),
		"_List":          reflect.ValueOf((*_go_hep_org_x_hep_groot_List)(nil)),
		"_Named":         reflect.ValueOf((*_go_hep_org_x_hep_groot_Named)(nil)),
		"_ObjArray":      reflect.ValueOf((*_go_hep_org_x_hep_groot_ObjArray)(nil)),
		"_ObjString":     reflect.ValueOf((*_go_hep_org_x_hep_groot_ObjString)(nil)),
		"_Object":        reflect.ValueOf((*_go_hep_org_x_hep_groot_Object)(nil)),
		"_Reader":        reflect.ValueOf((*_go_hep_org_x_hep_groot_Reader)(nil)),
		"_SeqCollection": reflect.ValueOf((*_go_hep_org_x_hep_groot_SeqCollection)(nil)),
	}
}

// _go_hep_org_x_hep_groot_Array is an interface wrapper for Array type
type _go_hep_org_x_hep_groot_Array struct {
	IValue interface{}
	WGet   func(i int) any
	WLen   func() int
	WSet   func(i int, v any)
}

func (W _go_hep_org_x_hep_groot_Array) Get(i int) any {
	return W.WGet(i)
}
func (W _go_hep_org_x_hep_groot_Array) Len() int {
	return W.WLen()
}
func (W _go_hep_org_x_hep_groot_Array) Set(i int, v any) {
	W.WSet(i, v)
}

// _go_hep_org_x_hep_groot_Collection is an interface wrapper for Collection type
type _go_hep_org_x_hep_groot_Collection struct {
	IValue interface{}
	WAt    func(i int) groot.Object
	WClass func() string
	WLast  func() int
	WLen   func() int
	WName  func() string
}

func (W _go_hep_org_x_hep_groot_Collection) At(i int) groot.Object {
	return W.WAt(i)
}
func (W _go_hep_org_x_hep_groot_Collection) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_Collection) Last() int {
	return W.WLast()
}
func (W _go_hep_org_x_hep_groot_Collection) Len() int {
	return W.WLen()
}
func (W _go_hep_org_x_hep_groot_Collection) Name() string {
	return W.WName()
}

// _go_hep_org_x_hep_groot_List is an interface wrapper for List type
type _go_hep_org_x_hep_groot_List struct {
	IValue interface{}
	WAt    func(i int) groot.Object
	WClass func() string
	WLast  func() int
	WLen   func() int
	WName  func() string
}

func (W _go_hep_org_x_hep_groot_List) At(i int) groot.Object {
	return W.WAt(i)
}
func (W _go_hep_org_x_hep_groot_List) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_List) Last() int {
	return W.WLast()
}
func (W _go_hep_org_x_hep_groot_List) Len() int {
	return W.WLen()
}
func (W _go_hep_org_x_hep_groot_List) Name() string {
	return W.WName()
}

// _go_hep_org_x_hep_groot_Named is an interface wrapper for Named type
type _go_hep_org_x_hep_groot_Named struct {
	IValue interface{}
	WClass func() string
	WName  func() string
	WTitle func() string
}

func (W _go_hep_org_x_hep_groot_Named) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_Named) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_Named) Title() string {
	return W.WTitle()
}

// _go_hep_org_x_hep_groot_ObjArray is an interface wrapper for ObjArray type
type _go_hep_org_x_hep_groot_ObjArray struct {
	IValue      interface{}
	WAt         func(i int) groot.Object
	WClass      func() string
	WLast       func() int
	WLen        func() int
	WLowerBound func() int
	WName       func() string
}

func (W _go_hep_org_x_hep_groot_ObjArray) At(i int) groot.Object {
	return W.WAt(i)
}
func (W _go_hep_org_x_hep_groot_ObjArray) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_ObjArray) Last() int {
	return W.WLast()
}
func (W _go_hep_org_x_hep_groot_ObjArray) Len() int {
	return W.WLen()
}
func (W _go_hep_org_x_hep_groot_ObjArray) LowerBound() int {
	return W.WLowerBound()
}
func (W _go_hep_org_x_hep_groot_ObjArray) Name() string {
	return W.WName()
}

// _go_hep_org_x_hep_groot_ObjString is an interface wrapper for ObjString type
type _go_hep_org_x_hep_groot_ObjString struct {
	IValue  interface{}
	WName   func() string
	WString func() string
}

func (W _go_hep_org_x_hep_groot_ObjString) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_ObjString) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}

// _go_hep_org_x_hep_groot_Object is an interface wrapper for Object type
type _go_hep_org_x_hep_groot_Object struct {
	IValue interface{}
	WClass func() string
}

func (W _go_hep_org_x_hep_groot_Object) Class() string {
	return W.WClass()
}

// _go_hep_org_x_hep_groot_Reader is an interface wrapper for Reader type
type _go_hep_org_x_hep_groot_Reader struct {
	IValue  interface{}
	WClose  func() error
	WRead   func(p []byte) (n int, err error)
	WReadAt func(p []byte, off int64) (n int, err error)
}

func (W _go_hep_org_x_hep_groot_Reader) Close() error {
	return W.WClose()
}
func (W _go_hep_org_x_hep_groot_Reader) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _go_hep_org_x_hep_groot_Reader) ReadAt(p []byte, off int64) (n int, err error) {
	return W.WReadAt(p, off)
}

// _go_hep_org_x_hep_groot_SeqCollection is an interface wrapper for SeqCollection type
type _go_hep_org_x_hep_groot_SeqCollection struct {
	IValue interface{}
	WAt    func(i int) groot.Object
	WClass func() string
	WLast  func() int
	WLen   func() int
	WName  func() string
}

func (W _go_hep_org_x_hep_groot_SeqCollection) At(i int) groot.Object {
	return W.WAt(i)
}
func (W _go_hep_org_x_hep_groot_SeqCollection) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_SeqCollection) Last() int {
	return W.WLast()
}
func (W _go_hep_org_x_hep_groot_SeqCollection) Len() int {
	return W.WLen()
}
func (W _go_hep_org_x_hep_groot_SeqCollection) Name() string {
	return W.WName()
}
