// Code generated by 'yaegi extract go-hep.org/x/hep/fit/minuit'. DO NOT EDIT.

package symbols

import (
	"go/constant"
	"go/token"
	"reflect"

	"go-hep.org/x/hep/fit/minuit"
)

func init() {
	Symbols["go-hep.org/x/hep/fit/minuit/minuit"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CallLimit":     reflect.ValueOf(minuit.CallLimit),
		"Chi2":          reflect.ValueOf(minuit.Chi2),
		"Chi2H1D":       reflect.ValueOf(minuit.Chi2H1D),
		"Converged":     reflect.ValueOf(minuit.Converged),
		"Exponential":   reflect.ValueOf(minuit.Exponential),
		"Failed":        reflect.ValueOf(minuit.Failed),
		"Fit":           reflect.ValueOf(minuit.Fit),
		"FitH1D":        reflect.ValueOf(minuit.FitH1D),
		"FitXY":         reflect.ValueOf(minuit.FitXY),
		"FuncOf":        reflect.ValueOf(minuit.FuncOf),
		"GausPars":      reflect.ValueOf(minuit.GausPars),
		"Gaussian":      reflect.ValueOf(minuit.Gaussian),
		"IFlagEnd":      reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"IFlagGrad":     reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"IFlagInit":     reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"IFlagVal":      reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"New":           reflect.ValueOf(minuit.New),
		"NotCalculated": reflect.ValueOf(minuit.NotCalculated),
		"Polynomial":    reflect.ValueOf(minuit.Polynomial),

		// type definitions
		"FCN":       reflect.ValueOf((*minuit.FCN)(nil)),
		"Minuit":    reflect.ValueOf((*minuit.Minuit)(nil)),
		"Model":     reflect.ValueOf((*minuit.Model)(nil)),
		"Par":       reflect.ValueOf((*minuit.Par)(nil)),
		"Parameter": reflect.ValueOf((*minuit.Parameter)(nil)),
		"Status":    reflect.ValueOf((*minuit.Status)(nil)),
	}
}
