// Code generated by 'yaegi extract go-hep.org/x/hep/groot/rtree/rdraw'. DO NOT EDIT.

package symbols

import (
	"reflect"

	"go-hep.org/x/hep/groot/rtree/rdraw"
)

func init() {
	Symbols["go-hep.org/x/hep/groot/rtree/rdraw/rdraw"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bins":   reflect.ValueOf(rdraw.Bins),
		"BinsY":  reflect.ValueOf(rdraw.BinsY),
		"BinsZ":  reflect.ValueOf(rdraw.BinsZ),
		"Cut":    reflect.ValueOf(rdraw.Cut),
		"Draw":   reflect.ValueOf(rdraw.Draw),
		"H1D":    reflect.ValueOf(rdraw.H1D),
		"H2D":    reflect.ValueOf(rdraw.H2D),
		"H3D":    reflect.ValueOf(rdraw.H3D),
		"Name":   reflect.ValueOf(rdraw.Name),
		"P1D":    reflect.ValueOf(rdraw.P1D),
		"Range":  reflect.ValueOf(rdraw.Range),
		"Title":  reflect.ValueOf(rdraw.Title),
		"Weight": reflect.ValueOf(rdraw.Weight),

		// type definitions
		"Option": reflect.ValueOf((*rdraw.Option)(nil)),
	}
}
