// Code generated by 'yaegi extract go-hep.org/x/hep/groot/rhist'. DO NOT EDIT.

package symbols

import (
	"reflect"

	"go-hep.org/x/hep/groot/rhist"
)

func init() {
	Symbols["go-hep.org/x/hep/groot/rhist/rhist"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewAxis":                 reflect.ValueOf(rhist.NewAxis),
		"NewF1":                   reflect.ValueOf(rhist.NewF1),
		"NewF2":                   reflect.ValueOf(rhist.NewF2),
		"NewF3":                   reflect.ValueOf(rhist.NewF3),
		"NewFormula":              reflect.ValueOf(rhist.NewFormula),
		"NewGraph2D":              reflect.ValueOf(rhist.NewGraph2D),
		"NewGraph2DAsymmErrors":   reflect.ValueOf(rhist.NewGraph2DAsymmErrors),
		"NewGraph2DErrors":        reflect.ValueOf(rhist.NewGraph2DErrors),
		"NewGraph2DFrom":          reflect.ValueOf(rhist.NewGraph2DFrom),
		"NewGraphAsymmErrorsFrom": reflect.ValueOf(rhist.NewGraphAsymmErrorsFrom),
		"NewGraphErrorsFrom":      reflect.ValueOf(rhist.NewGraphErrorsFrom),
		"NewGraphFrom":            reflect.ValueOf(rhist.NewGraphFrom),
		"NewGraphMultiErrorsFrom": reflect.ValueOf(rhist.NewGraphMultiErrorsFrom),
		"NewH1CFrom":              reflect.ValueOf(rhist.NewH1CFrom),
		"NewH1DFrom":              reflect.ValueOf(rhist.NewH1DFrom),
		"NewH1FFrom":              reflect.ValueOf(rhist.NewH1FFrom),
		"NewH1IFrom":              reflect.ValueOf(rhist.NewH1IFrom),
		"NewH1SFrom":              reflect.ValueOf(rhist.NewH1SFrom),
		"NewH2CFrom":              reflect.ValueOf(rhist.NewH2CFrom),
		"NewH2DFrom":              reflect.ValueOf(rhist.NewH2DFrom),
		"NewH2FFrom":              reflect.ValueOf(rhist.NewH2FFrom),
		"NewH2IFrom":              reflect.ValueOf(rhist.NewH2IFrom),
		"NewH2SFrom":              reflect.ValueOf(rhist.NewH2SFrom),
		"NewH3CFrom":              reflect.ValueOf(rhist.NewH3CFrom),
		"NewH3DFrom":              reflect.ValueOf(rhist.NewH3DFrom),
		"NewH3FFrom":              reflect.ValueOf(rhist.NewH3FFrom),
		"NewH3IFrom":              reflect.ValueOf(rhist.NewH3IFrom),
		"NewH3SFrom":              reflect.ValueOf(rhist.NewH3SFrom),

		// type definitions
		"Axis":               reflect.ValueOf((*rhist.Axis)(nil)),
		"ConfidenceLevel":    reflect.ValueOf((*rhist.ConfidenceLevel)(nil)),
		"Efficiency":         reflect.ValueOf((*rhist.Efficiency)(nil)),
		"F1":                 reflect.ValueOf((*rhist.F1)(nil)),
		"F1Composition":      reflect.ValueOf((*rhist.F1Composition)(nil)),
		"F1Convolution":      reflect.ValueOf((*rhist.F1Convolution)(nil)),
		"F1NormSum":          reflect.ValueOf((*rhist.F1NormSum)(nil)),
		"F1Parameters":       reflect.ValueOf((*rhist.F1Parameters)(nil)),
		"F2":                 reflect.ValueOf((*rhist.F2)(nil)),
		"F3":                 reflect.ValueOf((*rhist.F3)(nil)),
		"Formula":            reflect.ValueOf((*rhist.Formula)(nil)),
		"Graph":              reflect.ValueOf((*rhist.Graph)(nil)),
		"Graph2D":            reflect.ValueOf((*rhist.Graph2D)(nil)),
		"Graph2DAsymmErrors": reflect.ValueOf((*rhist.Graph2DAsymmErrors)(nil)),
		"Graph2DErrors":      reflect.ValueOf((*rhist.Graph2DErrors)(nil)),
		"GraphErrors":        reflect.ValueOf((*rhist.GraphErrors)(nil)),
		"H1":                 reflect.ValueOf((*rhist.H1)(nil)),
		"H1C":                reflect.ValueOf((*rhist.H1C)(nil)),
		"H1D":                reflect.ValueOf((*rhist.H1D)(nil)),
		"H1F":                reflect.ValueOf((*rhist.H1F)(nil)),
		"H1I":                reflect.ValueOf((*rhist.H1I)(nil)),
		"H1S":                reflect.ValueOf((*rhist.H1S)(nil)),
		"H2":                 reflect.ValueOf((*rhist.H2)(nil)),
		"H2C":                reflect.ValueOf((*rhist.H2C)(nil)),
		"H2D":                reflect.ValueOf((*rhist.H2D)(nil)),
		"H2F":                reflect.ValueOf((*rhist.H2F)(nil)),
		"H2I":                reflect.ValueOf((*rhist.H2I)(nil)),
		"H2S":                reflect.ValueOf((*rhist.H2S)(nil)),
		"H3":                 reflect.ValueOf((*rhist.H3)(nil)),
		"H3C":                reflect.ValueOf((*rhist.H3C)(nil)),
		"H3D":                reflect.ValueOf((*rhist.H3D)(nil)),
		"H3F":                reflect.ValueOf((*rhist.H3F)(nil)),
		"H3I":                reflect.ValueOf((*rhist.H3I)(nil)),
		"H3S":                reflect.ValueOf((*rhist.H3S)(nil)),
		"Limit":              reflect.ValueOf((*rhist.Limit)(nil)),
		"LimitDataSource":    reflect.ValueOf((*rhist.LimitDataSource)(nil)),
		"MultiGraph":         reflect.ValueOf((*rhist.MultiGraph)(nil)),
		"Profile1D":          reflect.ValueOf((*rhist.Profile1D)(nil)),
		"Profile2D":          reflect.ValueOf((*rhist.Profile2D)(nil)),
		"Profile3D":          reflect.ValueOf((*rhist.Profile3D)(nil)),
		"Scatter":            reflect.ValueOf((*rhist.Scatter)(nil)),

		// interface wrapper definitions
		"_Axis":          reflect.ValueOf((*_go_hep_org_x_hep_groot_rhist_Axis)(nil)),
		"_F1Composition": reflect.ValueOf((*_go_hep_org_x_hep_groot_rhist_F1Composition)(nil)),
		"_Graph":         reflect.ValueOf((*_go_hep_org_x_hep_groot_rhist_Graph)(nil)),
		"_GraphErrors":   reflect.ValueOf((*_go_hep_org_x_hep_groot_rhist_GraphErrors)(nil)),
		"_H1":            reflect.ValueOf((*_go_hep_org_x_hep_groot_rhist_H1)(nil)),
		"_H2":            reflect.ValueOf((*_go_hep_org_x_hep_groot_rhist_H2)(nil)),
		"_H3":            reflect.ValueOf((*_go_hep_org_x_hep_groot_rhist_H3)(nil)),
		"_MultiGraph":    reflect.ValueOf((*_go_hep_org_x_hep_groot_rhist_MultiGraph)(nil)),
	}
}

// _go_hep_org_x_hep_groot_rhist_Axis is an interface wrapper for Axis type
type _go_hep_org_x_hep_groot_rhist_Axis struct {
	IValue      interface{}
	WBinCenter  func(a0 int) float64
	WBinLowEdge func(a0 int) float64
	WBinWidth   func(a0 int) float64
	WClass      func() string
	WNBins      func() int
	WName       func() string
	WTitle      func() string
	WXBins      func() []float64
	WXMax       func() float64
	WXMin       func() float64
}

func (W _go_hep_org_x_hep_groot_rhist_Axis) BinCenter(a0 int) float64 {
	return W.WBinCenter(a0)
}
func (W _go_hep_org_x_hep_groot_rhist_Axis) BinLowEdge(a0 int) float64 {
	return W.WBinLowEdge(a0)
}
func (W _go_hep_org_x_hep_groot_rhist_Axis) BinWidth(a0 int) float64 {
	return W.WBinWidth(a0)
}
func (W _go_hep_org_x_hep_groot_rhist_Axis) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_rhist_Axis) NBins() int {
	return W.WNBins()
}
func (W _go_hep_org_x_hep_groot_rhist_Axis) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_rhist_Axis) Title() string {
	return W.WTitle()
}
func (W _go_hep_org_x_hep_groot_rhist_Axis) XBins() []float64 {
	return W.WXBins()
}
func (W _go_hep_org_x_hep_groot_rhist_Axis) XMax() float64 {
	return W.WXMax()
}
func (W _go_hep_org_x_hep_groot_rhist_Axis) XMin() float64 {
	return W.WXMin()
}

// _go_hep_org_x_hep_groot_rhist_F1Composition is an interface wrapper for F1Composition type
type _go_hep_org_x_hep_groot_rhist_F1Composition struct {
	IValue interface{}
	WClass func() string
}

func (W _go_hep_org_x_hep_groot_rhist_F1Composition) Class() string {
	return W.WClass()
}

// _go_hep_org_x_hep_groot_rhist_Graph is an interface wrapper for Graph type
type _go_hep_org_x_hep_groot_rhist_Graph struct {
	IValue interface{}
	WClass func() string
	WLen   func() int
	WName  func() string
	WTitle func() string
	WXY    func(i int) (float64, float64)
}

func (W _go_hep_org_x_hep_groot_rhist_Graph) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_rhist_Graph) Len() int {
	return W.WLen()
}
func (W _go_hep_org_x_hep_groot_rhist_Graph) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_rhist_Graph) Title() string {
	return W.WTitle()
}
func (W _go_hep_org_x_hep_groot_rhist_Graph) XY(i int) (float64, float64) {
	return W.WXY(i)
}

// _go_hep_org_x_hep_groot_rhist_GraphErrors is an interface wrapper for GraphErrors type
type _go_hep_org_x_hep_groot_rhist_GraphErrors struct {
	IValue  interface{}
	WClass  func() string
	WLen    func() int
	WName   func() string
	WTitle  func() string
	WXError func(i int) (float64, float64)
	WXY     func(i int) (float64, float64)
	WYError func(i int) (float64, float64)
}

func (W _go_hep_org_x_hep_groot_rhist_GraphErrors) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_rhist_GraphErrors) Len() int {
	return W.WLen()
}
func (W _go_hep_org_x_hep_groot_rhist_GraphErrors) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_rhist_GraphErrors) Title() string {
	return W.WTitle()
}
func (W _go_hep_org_x_hep_groot_rhist_GraphErrors) XError(i int) (float64, float64) {
	return W.WXError(i)
}
func (W _go_hep_org_x_hep_groot_rhist_GraphErrors) XY(i int) (float64, float64) {
	return W.WXY(i)
}
func (W _go_hep_org_x_hep_groot_rhist_GraphErrors) YError(i int) (float64, float64) {
	return W.WYError(i)
}

// _go_hep_org_x_hep_groot_rhist_H1 is an interface wrapper for H1 type
type _go_hep_org_x_hep_groot_rhist_H1 struct {
	IValue   interface{}
	WClass   func() string
	WEntries func() float64
	WName    func() string
	WSumW    func() float64
	WSumW2   func() float64
	WSumW2s  func() []float64
	WSumWX   func() float64
	WSumWX2  func() float64
	WTitle   func() string
}

func (W _go_hep_org_x_hep_groot_rhist_H1) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_rhist_H1) Entries() float64 {
	return W.WEntries()
}
func (W _go_hep_org_x_hep_groot_rhist_H1) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_rhist_H1) SumW() float64 {
	return W.WSumW()
}
func (W _go_hep_org_x_hep_groot_rhist_H1) SumW2() float64 {
	return W.WSumW2()
}
func (W _go_hep_org_x_hep_groot_rhist_H1) SumW2s() []float64 {
	return W.WSumW2s()
}
func (W _go_hep_org_x_hep_groot_rhist_H1) SumWX() float64 {
	return W.WSumWX()
}
func (W _go_hep_org_x_hep_groot_rhist_H1) SumWX2() float64 {
	return W.WSumWX2()
}
func (W _go_hep_org_x_hep_groot_rhist_H1) Title() string {
	return W.WTitle()
}

// _go_hep_org_x_hep_groot_rhist_H2 is an interface wrapper for H2 type
type _go_hep_org_x_hep_groot_rhist_H2 struct {
	IValue   interface{}
	WClass   func() string
	WEntries func() float64
	WName    func() string
	WSumW    func() float64
	WSumW2   func() float64
	WSumW2s  func() []float64
	WSumWX   func() float64
	WSumWX2  func() float64
	WSumWXY  func() float64
	WSumWY   func() float64
	WSumWY2  func() float64
	WTitle   func() string
}

func (W _go_hep_org_x_hep_groot_rhist_H2) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_rhist_H2) Entries() float64 {
	return W.WEntries()
}
func (W _go_hep_org_x_hep_groot_rhist_H2) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_rhist_H2) SumW() float64 {
	return W.WSumW()
}
func (W _go_hep_org_x_hep_groot_rhist_H2) SumW2() float64 {
	return W.WSumW2()
}
func (W _go_hep_org_x_hep_groot_rhist_H2) SumW2s() []float64 {
	return W.WSumW2s()
}
func (W _go_hep_org_x_hep_groot_rhist_H2) SumWX() float64 {
	return W.WSumWX()
}
func (W _go_hep_org_x_hep_groot_rhist_H2) SumWX2() float64 {
	return W.WSumWX2()
}
func (W _go_hep_org_x_hep_groot_rhist_H2) SumWXY() float64 {
	return W.WSumWXY()
}
func (W _go_hep_org_x_hep_groot_rhist_H2) SumWY() float64 {
	return W.WSumWY()
}
func (W _go_hep_org_x_hep_groot_rhist_H2) SumWY2() float64 {
	return W.WSumWY2()
}
func (W _go_hep_org_x_hep_groot_rhist_H2) Title() string {
	return W.WTitle()
}

// _go_hep_org_x_hep_groot_rhist_H3 is an interface wrapper for H3 type
type _go_hep_org_x_hep_groot_rhist_H3 struct {
	IValue   interface{}
	WClass   func() string
	WEntries func() float64
	WName    func() string
	WSumW    func() float64
	WSumW2   func() float64
	WSumW2s  func() []float64
	WSumWX   func() float64
	WSumWX2  func() float64
	WSumWXY  func() float64
	WSumWXZ  func() float64
	WSumWY   func() float64
	WSumWY2  func() float64
	WSumWYZ  func() float64
	WSumWZ   func() float64
	WSumWZ2  func() float64
	WTitle   func() string
}

func (W _go_hep_org_x_hep_groot_rhist_H3) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) Entries() float64 {
	return W.WEntries()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumW() float64 {
	return W.WSumW()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumW2() float64 {
	return W.WSumW2()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumW2s() []float64 {
	return W.WSumW2s()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumWX() float64 {
	return W.WSumWX()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumWX2() float64 {
	return W.WSumWX2()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumWXY() float64 {
	return W.WSumWXY()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumWXZ() float64 {
	return W.WSumWXZ()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumWY() float64 {
	return W.WSumWY()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumWY2() float64 {
	return W.WSumWY2()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumWYZ() float64 {
	return W.WSumWYZ()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumWZ() float64 {
	return W.WSumWZ()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) SumWZ2() float64 {
	return W.WSumWZ2()
}
func (W _go_hep_org_x_hep_groot_rhist_H3) Title() string {
	return W.WTitle()
}

// _go_hep_org_x_hep_groot_rhist_MultiGraph is an interface wrapper for MultiGraph type
type _go_hep_org_x_hep_groot_rhist_MultiGraph struct {
	IValue  interface{}
	WClass  func() string
	WGraphs func() []rhist.Graph
	WName   func() string
	WTitle  func() string
}

func (W _go_hep_org_x_hep_groot_rhist_MultiGraph) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_rhist_MultiGraph) Graphs() []rhist.Graph {
	return W.WGraphs()
}
func (W _go_hep_org_x_hep_groot_rhist_MultiGraph) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_rhist_MultiGraph) Title() string {
	return W.WTitle()
}
