// Code generated by 'yaegi extract go-hep.org/x/hep/cint/rt'. DO NOT EDIT.

package symbols

import (
	"reflect"

	"go-hep.org/x/hep/cint/rt"
)

func init() {
	Symbols["go-hep.org/x/hep/cint/rt/rt"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Draw":      reflect.ValueOf(rt.Draw),
		"Eval":      reflect.ValueOf(rt.Eval),
		"GFile":     reflect.ValueOf(rt.GFile),
		"GPad":      reflect.ValueOf(rt.GPad),
		"GRandom":   reflect.ValueOf(&rt.GRandom).Elem(),
		"GStyle":    reflect.ValueOf(&rt.GStyle).Elem(),
		"Get":       reflect.ValueOf(rt.Get),
		"NewCanvas": reflect.ValueOf(rt.NewCanvas),
		"NewF1":     reflect.ValueOf(rt.NewF1),
		"NewGraph":  reflect.ValueOf(rt.NewGraph),
		"NewRandom": reflect.ValueOf(rt.NewRandom),
		"OpenFile":  reflect.ValueOf(rt.OpenFile),
		"TreeDraw":  reflect.ValueOf(rt.TreeDraw),
		"TreeScan":  reflect.ValueOf(rt.TreeScan),
		"Write":     reflect.ValueOf(rt.Write),
		"WriteFile": reflect.ValueOf(rt.WriteFile),

		// type definitions
		"Canvas": reflect.ValueOf((*rt.Canvas)(nil)),
		"Graph":  reflect.ValueOf((*rt.Graph)(nil)),
		"Random": reflect.ValueOf((*rt.Random)(nil)),
		"Style":  reflect.ValueOf((*rt.Style)(nil)),
	}
}
