// Code generated by 'yaegi extract go-hep.org/x/hep/hbook/rootcnv'. DO NOT EDIT.

package symbols

import (
	"reflect"

	"go-hep.org/x/hep/hbook/rootcnv"
)

func init() {
	Symbols["go-hep.org/x/hep/hbook/rootcnv/rootcnv"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"FromH1D": reflect.ValueOf(rootcnv.FromH1D),
		"FromH2D": reflect.ValueOf(rootcnv.FromH2D),
		"FromS2D": reflect.ValueOf(rootcnv.FromS2D),
		"H1D":     reflect.ValueOf(rootcnv.H1D),
		"H2D":     reflect.ValueOf(rootcnv.H2D),
		"S2D":     reflect.ValueOf(rootcnv.S2D),
	}
}
