// Code generated by 'yaegi extract go-hep.org/x/hep/hplot'. DO NOT EDIT.

package symbols

import (
	"reflect"

	"go-hep.org/x/hep/hplot"
	"gonum.org/v1/plot/vg/draw"
)

func init() {
	Symbols["go-hep.org/x/hep/hplot/hplot"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultStyle":        reflect.ValueOf(&hplot.DefaultStyle).Elem(),
		"Dims":                reflect.ValueOf(hplot.Dims),
		"Figure":              reflect.ValueOf(hplot.Figure),
		"H3DXY":               reflect.ValueOf(hplot.H3DXY),
		"H3DXZ":               reflect.ValueOf(hplot.H3DXZ),
		"H3DYZ":               reflect.ValueOf(hplot.H3DYZ),
		"HInfoEntries":        reflect.ValueOf(hplot.HInfoEntries),
		"HInfoMean":           reflect.ValueOf(hplot.HInfoMean),
		"HInfoNone":           reflect.ValueOf(hplot.HInfoNone),
		"HInfoRMS":            reflect.ValueOf(hplot.HInfoRMS),
		"HInfoStdDev":         reflect.ValueOf(hplot.HInfoStdDev),
		"HInfoSummary":        reflect.ValueOf(hplot.HInfoSummary),
		"HLine":               reflect.ValueOf(hplot.HLine),
		"HStackOff":           reflect.ValueOf(hplot.HStackOff),
		"HStackOn":            reflect.ValueOf(hplot.HStackOn),
		"HiSteps":             reflect.ValueOf(hplot.HiSteps),
		"MidSteps":            reflect.ValueOf(hplot.MidSteps),
		"New":                 reflect.ValueOf(hplot.New),
		"NewBand":             reflect.ValueOf(hplot.NewBand),
		"NewBinnedErrBand":    reflect.ValueOf(hplot.NewBinnedErrBand),
		"NewFunction":         reflect.ValueOf(hplot.NewFunction),
		"NewGrid":             reflect.ValueOf(hplot.NewGrid),
		"NewH1D":              reflect.ValueOf(hplot.NewH1D),
		"NewH1FromValuer":     reflect.ValueOf(hplot.NewH1FromValuer),
		"NewH1FromXYer":       reflect.ValueOf(hplot.NewH1FromXYer),
		"NewH2D":              reflect.ValueOf(hplot.NewH2D),
		"NewH3D":              reflect.ValueOf(hplot.NewH3D),
		"NewH3DProfile":       reflect.ValueOf(hplot.NewH3DProfile),
		"NewH3DSlice":         reflect.ValueOf(hplot.NewH3DSlice),
		"NewHStack":           reflect.ValueOf(hplot.NewHStack),
		"NewLabel":            reflect.ValueOf(hplot.NewLabel),
		"NewLegend":           reflect.ValueOf(hplot.NewLegend),
		"NewLine":             reflect.ValueOf(hplot.NewLine),
		"NewLinePoints":       reflect.ValueOf(hplot.NewLinePoints),
		"NewRatioPlot":        reflect.ValueOf(hplot.NewRatioPlot),
		"NewS2D":              reflect.ValueOf(hplot.NewS2D),
		"NewScatter":          reflect.ValueOf(hplot.NewScatter),
		"NewStyle":            reflect.ValueOf(hplot.NewStyle),
		"NewTiledPlot":        reflect.ValueOf(hplot.NewTiledPlot),
		"NoSteps":             reflect.ValueOf(hplot.NoSteps),
		"PostSteps":           reflect.ValueOf(hplot.PostSteps),
		"PreSteps":            reflect.ValueOf(hplot.PreSteps),
		"Save":                reflect.ValueOf(hplot.Save),
		"Show":                reflect.ValueOf(hplot.Show),
		"VLine":               reflect.ValueOf(hplot.VLine),
		"WithBand":            reflect.ValueOf(hplot.WithBand),
		"WithBorder":          reflect.ValueOf(hplot.WithBorder),
		"WithDPI":             reflect.ValueOf(hplot.WithDPI),
		"WithGlyphStyle":      reflect.ValueOf(hplot.WithGlyphStyle),
		"WithHInfo":           reflect.ValueOf(hplot.WithHInfo),
		"WithLabelAutoAdjust": reflect.ValueOf(hplot.WithLabelAutoAdjust),
		"WithLabelNormalized": reflect.ValueOf(hplot.WithLabelNormalized),
		"WithLabelTextStyle":  reflect.ValueOf(hplot.WithLabelTextStyle),
		"WithLatexHandler":    reflect.ValueOf(hplot.WithLatexHandler),
		"WithLegend":          reflect.ValueOf(hplot.WithLegend),
		"WithLogY":            reflect.ValueOf(hplot.WithLogY),
		"WithStepsKind":       reflect.ValueOf(hplot.WithStepsKind),
		"WithXErrBars":        reflect.ValueOf(hplot.WithXErrBars),
		"WithYErrBars":        reflect.ValueOf(hplot.WithYErrBars),
		"WriterTo":            reflect.ValueOf(hplot.WriterTo),
		"ZipXY":               reflect.ValueOf(hplot.ZipXY),

		// type definitions
		"Band":          reflect.ValueOf((*hplot.Band)(nil)),
		"BinnedErrBand": reflect.ValueOf((*hplot.BinnedErrBand)(nil)),
		"Border":        reflect.ValueOf((*hplot.Border)(nil)),
		"Drawer":        reflect.ValueOf((*hplot.Drawer)(nil)),
		"Fig":           reflect.ValueOf((*hplot.Fig)(nil)),
		"FigOption":     reflect.ValueOf((*hplot.FigOption)(nil)),
		"FreqTicks":     reflect.ValueOf((*hplot.FreqTicks)(nil)),
		"Function":      reflect.ValueOf((*hplot.Function)(nil)),
		"H1D":           reflect.ValueOf((*hplot.H1D)(nil)),
		"H2D":           reflect.ValueOf((*hplot.H2D)(nil)),
		"H3DPlane":      reflect.ValueOf((*hplot.H3DPlane)(nil)),
		"HInfoStyle":    reflect.ValueOf((*hplot.HInfoStyle)(nil)),
		"HInfos":        reflect.ValueOf((*hplot.HInfos)(nil)),
		"HStack":        reflect.ValueOf((*hplot.HStack)(nil)),
		"HStackKind":    reflect.ValueOf((*hplot.HStackKind)(nil)),
		"HorizLine":     reflect.ValueOf((*hplot.HorizLine)(nil)),
		"Label":         reflect.ValueOf((*hplot.Label)(nil)),
		"LabelOption":   reflect.ValueOf((*hplot.LabelOption)(nil)),
		"Legend":        reflect.ValueOf((*hplot.Legend)(nil)),
		"NoTicks":       reflect.ValueOf((*hplot.NoTicks)(nil)),
		"Options":       reflect.ValueOf((*hplot.Options)(nil)),
		"Plot":          reflect.ValueOf((*hplot.Plot)(nil)),
		"RatioPlot":     reflect.ValueOf((*hplot.RatioPlot)(nil)),
		"S2D":           reflect.ValueOf((*hplot.S2D)(nil)),
		"StepsKind":     reflect.ValueOf((*hplot.StepsKind)(nil)),
		"Style":         reflect.ValueOf((*hplot.Style)(nil)),
		"Ticks":         reflect.ValueOf((*hplot.Ticks)(nil)),
		"TiledPlot":     reflect.ValueOf((*hplot.TiledPlot)(nil)),
		"VertLine":      reflect.ValueOf((*hplot.VertLine)(nil)),

		// interface wrapper definitions
		"_Drawer": reflect.ValueOf((*_go_hep_org_x_hep_hplot_Drawer)(nil)),
	}
}

// _go_hep_org_x_hep_hplot_Drawer is an interface wrapper for Drawer type
type _go_hep_org_x_hep_hplot_Drawer struct {
	IValue interface{}
	WDraw  func(a0 draw.Canvas)
}

func (W _go_hep_org_x_hep_hplot_Drawer) Draw(a0 draw.Canvas) {
	W.WDraw(a0)
}
