// Code generated by 'yaegi extract go-hep.org/x/hep/hbook/ntup/ntroot'. DO NOT EDIT.

package symbols

import (
	"reflect"

	"go-hep.org/x/hep/hbook/ntup/ntroot"
)

func init() {
	Symbols["go-hep.org/x/hep/hbook/ntup/ntroot/ntroot"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Open": reflect.ValueOf(ntroot.Open),
	}
}
