// Code generated by 'yaegi extract go-hep.org/x/hep/groot/rtree/rdf'. DO NOT EDIT.

package symbols

import (
	"reflect"

	"go-hep.org/x/hep/groot/rtree/rdf"
)

func init() {
	Symbols["go-hep.org/x/hep/groot/rtree/rdf/rdf"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bins":     reflect.ValueOf(rdf.Bins),
		"BinsY":    reflect.ValueOf(rdf.BinsY),
		"BinsZ":    reflect.ValueOf(rdf.BinsZ),
		"HName":    reflect.ValueOf(rdf.HName),
		"HWeight":  reflect.ValueOf(rdf.HWeight),
		"New":      reflect.ValueOf(rdf.New),
		"NewRange": reflect.ValueOf(rdf.NewRange),

		// type definitions
		"CutInfo": reflect.ValueOf((*rdf.CutInfo)(nil)),
		"Frame":   reflect.ValueOf((*rdf.Frame)(nil)),
		"HOption": reflect.ValueOf((*rdf.HOption)(nil)),
	}
}
