// Code generated by 'yaegi extract go-hep.org/x/hep/groot/rtree'. DO NOT EDIT.

package symbols

import (
	"reflect"

	"go-hep.org/x/hep/groot/rtree"
)

func init() {
	Symbols["go-hep.org/x/hep/groot/rtree/rtree"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Chain":               reflect.ValueOf(rtree.Chain),
		"ChainOf":             reflect.ValueOf(rtree.ChainOf),
		"Copy":                reflect.ValueOf(rtree.Copy),
		"FileOf":              reflect.ValueOf(rtree.FileOf),
		"Join":                reflect.ValueOf(rtree.Join),
		"NewReadVars":         reflect.ValueOf(rtree.NewReadVars),
		"NewReader":           reflect.ValueOf(rtree.NewReader),
		"NewWriter":           reflect.ValueOf(rtree.NewWriter),
		"ReadVarsFromStruct":  reflect.ValueOf(rtree.ReadVarsFromStruct),
		"WithBasketSize":      reflect.ValueOf(rtree.WithBasketSize),
		"WithLZ4":             reflect.ValueOf(rtree.WithLZ4),
		"WithLZMA":            reflect.ValueOf(rtree.WithLZMA),
		"WithPrefetchBaskets": reflect.ValueOf(rtree.WithPrefetchBaskets),
		"WithRange":           reflect.ValueOf(rtree.WithRange),
		"WithSplitLevel":      reflect.ValueOf(rtree.WithSplitLevel),
		"WithTitle":           reflect.ValueOf(rtree.WithTitle),
		"WithZlib":            reflect.ValueOf(rtree.WithZlib),
		"WithZstd":            reflect.ValueOf(rtree.WithZstd),
		"WithoutCompression":  reflect.ValueOf(rtree.WithoutCompression),
		"WriteVarsFromStruct": reflect.ValueOf(rtree.WriteVarsFromStruct),
		"WriteVarsFromTree":   reflect.ValueOf(rtree.WriteVarsFromTree),

		// type definitions
		"Basket":      reflect.ValueOf((*rtree.Basket)(nil)),
		"Branch":      reflect.ValueOf((*rtree.Branch)(nil)),
		"Leaf":        reflect.ValueOf((*rtree.Leaf)(nil)),
		"LeafB":       reflect.ValueOf((*rtree.LeafB)(nil)),
		"LeafC":       reflect.ValueOf((*rtree.LeafC)(nil)),
		"LeafD":       reflect.ValueOf((*rtree.LeafD)(nil)),
		"LeafD32":     reflect.ValueOf((*rtree.LeafD32)(nil)),
		"LeafF":       reflect.ValueOf((*rtree.LeafF)(nil)),
		"LeafF16":     reflect.ValueOf((*rtree.LeafF16)(nil)),
		"LeafG":       reflect.ValueOf((*rtree.LeafG)(nil)),
		"LeafI":       reflect.ValueOf((*rtree.LeafI)(nil)),
		"LeafL":       reflect.ValueOf((*rtree.LeafL)(nil)),
		"LeafO":       reflect.ValueOf((*rtree.LeafO)(nil)),
		"LeafS":       reflect.ValueOf((*rtree.LeafS)(nil)),
		"RCtx":        reflect.ValueOf((*rtree.RCtx)(nil)),
		"ReadOption":  reflect.ValueOf((*rtree.ReadOption)(nil)),
		"ReadVar":     reflect.ValueOf((*rtree.ReadVar)(nil)),
		"Reader":      reflect.ValueOf((*rtree.Reader)(nil)),
		"Tree":        reflect.ValueOf((*rtree.Tree)(nil)),
		"WriteOption": reflect.ValueOf((*rtree.WriteOption)(nil)),
		"WriteVar":    reflect.ValueOf((*rtree.WriteVar)(nil)),
		"Writer":      reflect.ValueOf((*rtree.Writer)(nil)),

		// interface wrapper definitions
		"_Branch": reflect.ValueOf((*_go_hep_org_x_hep_groot_rtree_Branch)(nil)),
		"_Leaf":   reflect.ValueOf((*_go_hep_org_x_hep_groot_rtree_Leaf)(nil)),
		"_Tree":   reflect.ValueOf((*_go_hep_org_x_hep_groot_rtree_Tree)(nil)),
		"_Writer": reflect.ValueOf((*_go_hep_org_x_hep_groot_rtree_Writer)(nil)),
	}
}

// _go_hep_org_x_hep_groot_rtree_Branch is an interface wrapper for Branch type
type _go_hep_org_x_hep_groot_rtree_Branch struct {
	IValue    interface{}
	WBranch   func(name string) rtree.Branch
	WBranches func() []rtree.Branch
	WClass    func() string
	WGoType   func() reflect.Type
	WLeaf     func(name string) rtree.Leaf
	WLeaves   func() []rtree.Leaf
	WName     func() string
	WTitle    func() string
}

func (W _go_hep_org_x_hep_groot_rtree_Branch) Branch(name string) rtree.Branch {
	return W.WBranch(name)
}
func (W _go_hep_org_x_hep_groot_rtree_Branch) Branches() []rtree.Branch {
	return W.WBranches()
}
func (W _go_hep_org_x_hep_groot_rtree_Branch) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_rtree_Branch) GoType() reflect.Type {
	return W.WGoType()
}
func (W _go_hep_org_x_hep_groot_rtree_Branch) Leaf(name string) rtree.Leaf {
	return W.WLeaf(name)
}
func (W _go_hep_org_x_hep_groot_rtree_Branch) Leaves() []rtree.Leaf {
	return W.WLeaves()
}
func (W _go_hep_org_x_hep_groot_rtree_Branch) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_rtree_Branch) Title() string {
	return W.WTitle()
}

// _go_hep_org_x_hep_groot_rtree_Leaf is an interface wrapper for Leaf type
type _go_hep_org_x_hep_groot_rtree_Leaf struct {
	IValue      interface{}
	WBranch     func() rtree.Branch
	WClass      func() string
	WHasRange   func() bool
	WIsUnsigned func() bool
	WKind       func() reflect.Kind
	WLeafCount  func() rtree.Leaf
	WLen        func() int
	WLenType    func() int
	WName       func() string
	WOffset     func() int
	WShape      func() []int
	WTitle      func() string
	WType       func() reflect.Type
	WTypeName   func() string
}

func (W _go_hep_org_x_hep_groot_rtree_Leaf) Branch() rtree.Branch {
	return W.WBranch()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) HasRange() bool {
	return W.WHasRange()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) IsUnsigned() bool {
	return W.WIsUnsigned()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) Kind() reflect.Kind {
	return W.WKind()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) LeafCount() rtree.Leaf {
	return W.WLeafCount()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) Len() int {
	return W.WLen()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) LenType() int {
	return W.WLenType()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) Offset() int {
	return W.WOffset()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) Shape() []int {
	return W.WShape()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) Title() string {
	return W.WTitle()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) Type() reflect.Type {
	return W.WType()
}
func (W _go_hep_org_x_hep_groot_rtree_Leaf) TypeName() string {
	return W.WTypeName()
}

// _go_hep_org_x_hep_groot_rtree_Tree is an interface wrapper for Tree type
type _go_hep_org_x_hep_groot_rtree_Tree struct {
	IValue    interface{}
	WBranch   func(name string) rtree.Branch
	WBranches func() []rtree.Branch
	WClass    func() string
	WEntries  func() int64
	WLeaf     func(name string) rtree.Leaf
	WLeaves   func() []rtree.Leaf
	WName     func() string
	WTitle    func() string
}

func (W _go_hep_org_x_hep_groot_rtree_Tree) Branch(name string) rtree.Branch {
	return W.WBranch(name)
}
func (W _go_hep_org_x_hep_groot_rtree_Tree) Branches() []rtree.Branch {
	return W.WBranches()
}
func (W _go_hep_org_x_hep_groot_rtree_Tree) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_rtree_Tree) Entries() int64 {
	return W.WEntries()
}
func (W _go_hep_org_x_hep_groot_rtree_Tree) Leaf(name string) rtree.Leaf {
	return W.WLeaf(name)
}
func (W _go_hep_org_x_hep_groot_rtree_Tree) Leaves() []rtree.Leaf {
	return W.WLeaves()
}
func (W _go_hep_org_x_hep_groot_rtree_Tree) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_rtree_Tree) Title() string {
	return W.WTitle()
}

// _go_hep_org_x_hep_groot_rtree_Writer is an interface wrapper for Writer type
type _go_hep_org_x_hep_groot_rtree_Writer struct {
	IValue    interface{}
	WBranch   func(name string) rtree.Branch
	WBranches func() []rtree.Branch
	WClass    func() string
	WClose    func() error
	WEntries  func() int64
	WFlush    func() error
	WLeaf     func(name string) rtree.Leaf
	WLeaves   func() []rtree.Leaf
	WName     func() string
	WTitle    func() string
	WWrite    func() (int, error)
}

func (W _go_hep_org_x_hep_groot_rtree_Writer) Branch(name string) rtree.Branch {
	return W.WBranch(name)
}
func (W _go_hep_org_x_hep_groot_rtree_Writer) Branches() []rtree.Branch {
	return W.WBranches()
}
func (W _go_hep_org_x_hep_groot_rtree_Writer) Class() string {
	return W.WClass()
}
func (W _go_hep_org_x_hep_groot_rtree_Writer) Close() error {
	return W.WClose()
}
func (W _go_hep_org_x_hep_groot_rtree_Writer) Entries() int64 {
	return W.WEntries()
}
func (W _go_hep_org_x_hep_groot_rtree_Writer) Flush() error {
	return W.WFlush()
}
func (W _go_hep_org_x_hep_groot_rtree_Writer) Leaf(name string) rtree.Leaf {
	return W.WLeaf(name)
}
func (W _go_hep_org_x_hep_groot_rtree_Writer) Leaves() []rtree.Leaf {
	return W.WLeaves()
}
func (W _go_hep_org_x_hep_groot_rtree_Writer) Name() string {
	return W.WName()
}
func (W _go_hep_org_x_hep_groot_rtree_Writer) Title() string {
	return W.WTitle()
}
func (W _go_hep_org_x_hep_groot_rtree_Writer) Write() (int, error) {
	return W.WWrite()
}
