// Code generated by 'yaegi extract go-hep.org/x/hep/fit'. DO NOT EDIT.

package symbols

import (
	"reflect"

	"go-hep.org/x/hep/fit"
)

func init() {
	Symbols["go-hep.org/x/hep/fit/fit"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Curve1D": reflect.ValueOf(fit.Curve1D),
		"CurveND": reflect.ValueOf(fit.CurveND),
		"H1D":     reflect.ValueOf(fit.H1D),
		"Poly":    reflect.ValueOf(fit.Poly),

		// type definitions
		"Func1D": reflect.ValueOf((*fit.Func1D)(nil)),
		"FuncND": reflect.ValueOf((*fit.FuncND)(nil)),
	}
}
