// Code generated by 'yaegi extract go-hep.org/x/hep/groot/riofs'. DO NOT EDIT.

package symbols

import (
	"reflect"

	"go-hep.org/x/hep/groot/riofs"
	"go-hep.org/x/hep/groot/root"
)

func init() {
	Symbols["go-hep.org/x/hep/groot/riofs/riofs"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Create":                  reflect.ValueOf(riofs.Create),
		"Dir":                     reflect.ValueOf(riofs.Dir),
		"Drivers":                 reflect.ValueOf(riofs.Drivers),
		"ErrReadOnly":             reflect.ValueOf(&riofs.ErrReadOnly).Elem(),
		"KeyFromDir":              reflect.ValueOf(riofs.KeyFromDir),
		"NewKey":                  reflect.ValueOf(riofs.NewKey),
		"NewKeyForBasketInternal": reflect.ValueOf(riofs.NewKeyForBasketInternal),
		"NewReader":               reflect.ValueOf(riofs.NewReader),
		"Open":                    reflect.ValueOf(riofs.Open),
		"RMemFile":                reflect.ValueOf(riofs.RMemFile),
		"Register":                reflect.ValueOf(riofs.Register),
		"RegisterWriter":          reflect.ValueOf(riofs.RegisterWriter),
		"SkipDir":                 reflect.ValueOf(&riofs.SkipDir).Elem(),
		"Walk":                    reflect.ValueOf(riofs.Walk),
		"WithKeyCompression":      reflect.ValueOf(riofs.WithKeyCompression),
		"WithLZ4":                 reflect.ValueOf(riofs.WithLZ4),
		"WithLZMA":                reflect.ValueOf(riofs.WithLZMA),
		"WithZlib":                reflect.ValueOf(riofs.WithZlib),
		"WithZstd":                reflect.ValueOf(riofs.WithZstd),
		"WithoutCompression":      reflect.ValueOf(riofs.WithoutCompression),
		"WriteDrivers":            reflect.ValueOf(riofs.WriteDrivers),

		// type definitions
		"Directory":  reflect.ValueOf((*riofs.Directory)(nil)),
		"File":       reflect.ValueOf((*riofs.File)(nil)),
		"FileOption": reflect.ValueOf((*riofs.FileOption)(nil)),
		"Key":        reflect.ValueOf((*riofs.Key)(nil)),
		"KeyOption":  reflect.ValueOf((*riofs.KeyOption)(nil)),
		"Reader":     reflect.ValueOf((*riofs.Reader)(nil)),
		"SetFiler":   reflect.ValueOf((*riofs.SetFiler)(nil)),
		"WalkFunc":   reflect.ValueOf((*riofs.WalkFunc)(nil)),
		"Writer":     reflect.ValueOf((*riofs.Writer)(nil)),

		// interface wrapper definitions
		"_Directory": reflect.ValueOf((*_go_hep_org_x_hep_groot_riofs_Directory)(nil)),
		"_Reader":    reflect.ValueOf((*_go_hep_org_x_hep_groot_riofs_Reader)(nil)),
		"_SetFiler":  reflect.ValueOf((*_go_hep_org_x_hep_groot_riofs_SetFiler)(nil)),
		"_Writer":    reflect.ValueOf((*_go_hep_org_x_hep_groot_riofs_Writer)(nil)),
	}
}

// _go_hep_org_x_hep_groot_riofs_Directory is an interface wrapper for Directory type
type _go_hep_org_x_hep_groot_riofs_Directory struct {
	IValue  interface{}
	WGet    func(namecycle string) (root.Object, error)
	WKeys   func() []riofs.Key
	WMkdir  func(name string) (riofs.Directory, error)
	WParent func() riofs.Directory
	WPut    func(name string, v root.Object) error
}

func (W _go_hep_org_x_hep_groot_riofs_Directory) Get(namecycle string) (root.Object, error) {
	return W.WGet(namecycle)
}
func (W _go_hep_org_x_hep_groot_riofs_Directory) Keys() []riofs.Key {
	return W.WKeys()
}
func (W _go_hep_org_x_hep_groot_riofs_Directory) Mkdir(name string) (riofs.Directory, error) {
	return W.WMkdir(name)
}
func (W _go_hep_org_x_hep_groot_riofs_Directory) Parent() riofs.Directory {
	return W.WParent()
}
func (W _go_hep_org_x_hep_groot_riofs_Directory) Put(name string, v root.Object) error {
	return W.WPut(name, v)
}

// _go_hep_org_x_hep_groot_riofs_Reader is an interface wrapper for Reader type
type _go_hep_org_x_hep_groot_riofs_Reader struct {
	IValue  interface{}
	WClose  func() error
	WRead   func(p []byte) (n int, err error)
	WReadAt func(p []byte, off int64) (n int, err error)
}

func (W _go_hep_org_x_hep_groot_riofs_Reader) Close() error {
	return W.WClose()
}
func (W _go_hep_org_x_hep_groot_riofs_Reader) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _go_hep_org_x_hep_groot_riofs_Reader) ReadAt(p []byte, off int64) (n int, err error) {
	return W.WReadAt(p, off)
}

// _go_hep_org_x_hep_groot_riofs_SetFiler is an interface wrapper for SetFiler type
type _go_hep_org_x_hep_groot_riofs_SetFiler struct {
	IValue   interface{}
	WSetFile func(f *riofs.File)
}

func (W _go_hep_org_x_hep_groot_riofs_SetFiler) SetFile(f *riofs.File) {
	W.WSetFile(f)
}

// _go_hep_org_x_hep_groot_riofs_Writer is an interface wrapper for Writer type
type _go_hep_org_x_hep_groot_riofs_Writer struct {
	IValue   interface{}
	WClose   func() error
	WWrite   func(p []byte) (n int, err error)
	WWriteAt func(p []byte, off int64) (n int, err error)
}

func (W _go_hep_org_x_hep_groot_riofs_Writer) Close() error {
	return W.WClose()
}
func (W _go_hep_org_x_hep_groot_riofs_Writer) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}
func (W _go_hep_org_x_hep_groot_riofs_Writer) WriteAt(p []byte, off int64) (n int, err error) {
	return W.WWriteAt(p, off)
}
