// Copyright ©2018 The go-hep Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package protocol contains the XRootD protocol specific types
// and methods to handle them, such as marshalling and unmarshalling requests.
package xrdproto // import "go-hep.org/x/hep/xrootd/xrdproto"

import (
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"path"
	"strings"
	"time"

	"go-hep.org/x/hep/xrootd/internal/xrdenc"
	"go-hep.org/x/hep/xrootd/xrdfs"
)

// Request is a XRootD request issued to a server.
type Request interface {
	// ReqID uniquely identifies the type of a request.
	ReqID() uint16

	// ShouldSign indicates whether this request should be signed if security level is SignLikely.
	// For the list of actual examples see XRootD protocol specification v. 3.1.0, p.76.
	ShouldSign() bool

	Marshaler
	Unmarshaler
}

// Response is a XRootD response returned by the server
type Response interface {
	RespID() uint16
	Marshaler
	Unmarshaler
}

// Marshaler is the interface implemented by a type that can marshal itself
// into a binary form, following the XRootD protocol.
//
// MarshalXrd encodes the receiver into a binary form and returns the result.
type Marshaler interface {
	MarshalXrd(enc *xrdenc.WBuffer) error
}

// Unmarshaler is the interface implemented by a type that can
// unmarshal a binary representation of itself, following the XRootD protocol.
//
// UnmarshalXrd must be able to decode the form generated by MarshalXrd.
// UnmarshalXrd must copy the data if it wishes to retain the data after
// returning.
type Unmarshaler interface {
	UnmarshalXrd(dec *xrdenc.RBuffer) error
}

// ResponseStatus is the status code indicating how the request completed.
type ResponseStatus uint16

const (
	// Ok indicates that request fully completed and no addition responses will be forthcoming.
	Ok ResponseStatus = 0
	// OkSoFar indicates that server provides partial response and client should be prepared
	// to receive additional responses on same stream.
	OkSoFar ResponseStatus = 4000
	// Error indicates that an error occurred during request handling.
	// Error code and error message are sent as part of response (see xrootd protocol specification v3.1.0, p. 27).
	Error ResponseStatus = 4003
	// Redirect indicates that the client must re-issue the request to another server.
	Redirect ResponseStatus = 4004
	// Attn indicates an asynchronous attention response from the server. When
	// its action code is AsyncResp, it wraps a deferred response for another
	// stream (e.g. the completion of a third-party copy triggered by sync).
	Attn ResponseStatus = 4001
	// AuthMore indicates that the server needs more information to complete
	// authentication; the response data carries a challenge and the client
	// must send a follow-up auth request. Used by multi-round mechanisms such
	// as GSI.
	AuthMore ResponseStatus = 4002
	// Wait indicates that the client must wait the indicated number of seconds and retry the request.
	Wait ResponseStatus = 4005
	// WaitResp indicates that the server has deferred the response: the real
	// response for this request will arrive later on the same stream. Used by
	// third-party copy, where the source open reply is held until the transfer
	// completes.
	WaitResp ResponseStatus = 4006
	// Status indicates that the request was processed and the response is a
	// kXR_status frame: a CRC-protected StatusBody, an operation-specific
	// info tail, and possibly trailing data whose length is carried in the
	// body itself (outside the response-header data length).
	Status ResponseStatus = 4007
)

// AsyncResp is the action code (in an Attn response body) marking an
// asynchronous delayed response for another stream.
const AsyncResp int32 = 5008

// WaitResponse is the response indicating that the client must wait and retry the request.
// See http://xrootd.org/doc/dev45/XRdv310.pdf, p. 35 for details.
type WaitResponse struct {
	Duration time.Duration
}

// MarshalXrd implements Marshaler.
func (o WaitResponse) MarshalXrd(wBuffer *xrdenc.WBuffer) error {
	wBuffer.WriteI32(int32(o.Duration.Seconds()))
	return nil
}

// UnmarshalXrd implements Unmarshaler.
func (o *WaitResponse) UnmarshalXrd(rBuffer *xrdenc.RBuffer) error {
	o.Duration = time.Second * time.Duration(rBuffer.ReadI32())
	return rBuffer.Err()
}

// ServerError is the error returned by the XRootD server as part of response to the request.
type ServerError struct {
	Code    ServerErrorCode
	Message string
}

// ServerErrorCode is the code of the error returned by the XRootD server as part of response to the request.
type ServerErrorCode int32

// The error codes an XRootD server may return in a kXR_error response.
const (
	ArgInvalid          ServerErrorCode = 3000 // ArgInvalid indicates that an argument of the request is invalid.
	ArgMissing          ServerErrorCode = 3001 // ArgMissing indicates that a required argument is absent.
	ArgTooLong          ServerErrorCode = 3002 // ArgTooLong indicates that an argument exceeds the length the server accepts.
	FileLocked          ServerErrorCode = 3003 // FileLocked indicates that the file is held by another client.
	FileNotOpen         ServerErrorCode = 3004 // FileNotOpen indicates that the request names a handle that is not open.
	FSError             ServerErrorCode = 3005 // FSError indicates that the server's filesystem reported an error.
	InvalidRequest      ServerErrorCode = 3006 // InvalidRequest indicates that request is invalid.
	IOError             ServerErrorCode = 3007 // IOError indicates that an IO error has occurred on the server side.
	NoMemory            ServerErrorCode = 3008 // NoMemory indicates that the server could not allocate what the request needs.
	NoSpace             ServerErrorCode = 3009 // NoSpace indicates that the server has no room for the data.
	NotAuthorized       ServerErrorCode = 3010 // NotAuthorized indicates that user was not authorized for operation.
	NotFound            ServerErrorCode = 3011 // NotFound indicates that path was not found on the remote server.
	InternalServerError ServerErrorCode = 3012 // InternalServerError indicates that the server failed for a reason of its own.
	Unsupported         ServerErrorCode = 3013 // Unsupported indicates that the server does not implement the request.
	NoServer            ServerErrorCode = 3014 // NoServer indicates that no server able to handle the request was found.
	NotFile             ServerErrorCode = 3015 // NotFile indicates that the path names something that is not a regular file.
	IsDirectory         ServerErrorCode = 3016 // IsDirectory indicates that the path names a directory.
	Cancelled           ServerErrorCode = 3017 // Cancelled indicates that the request was cancelled.
	ItExists            ServerErrorCode = 3018 // ItExists indicates that the path already exists.
	ChkSumErr           ServerErrorCode = 3019 // ChkSumErr indicates that a checksum did not match.
	InProgress          ServerErrorCode = 3020 // InProgress indicates that the request is already being served.
	OverQuota           ServerErrorCode = 3021 // OverQuota indicates that the user's quota is exhausted.
	SigVerErr           ServerErrorCode = 3022 // SigVerErr indicates that a request signature did not verify.
	DecryptErr          ServerErrorCode = 3023 // DecryptErr indicates that the server could not decrypt what it was sent.
	Overloaded          ServerErrorCode = 3024 // Overloaded indicates that the server is too busy to serve the request.
	FSReadOnly          ServerErrorCode = 3025 // FSReadOnly indicates that the server's filesystem does not accept writes.
	BadPayload          ServerErrorCode = 3026 // BadPayload indicates that the request payload is malformed.
	AttrNotFound        ServerErrorCode = 3027 // AttrNotFound indicates that an extended attribute does not exist.
	TLSRequired         ServerErrorCode = 3028 // TLSRequired indicates that the server requires the request to be encrypted.
	NoReplicas          ServerErrorCode = 3029 // NoReplicas indicates that no replica of the file is available.
	AuthFailed          ServerErrorCode = 3030 // AuthFailed indicates that authentication did not succeed.
	Impossible          ServerErrorCode = 3031 // Impossible indicates that the request cannot be satisfied as asked.
	Conflict            ServerErrorCode = 3032 // Conflict indicates that the request conflicts with one already in flight.
	TooManyErrs         ServerErrorCode = 3033 // TooManyErrs indicates that the server gave up after repeated failures.
)

// serverErrorNames holds the specification's name for each code, so an error
// reads as something a server administrator can look up rather than a number.
var serverErrorNames = map[ServerErrorCode]string{
	ArgInvalid:          "kXR_ArgInvalid",
	ArgMissing:          "kXR_ArgMissing",
	ArgTooLong:          "kXR_ArgTooLong",
	FileLocked:          "kXR_FileLocked",
	FileNotOpen:         "kXR_FileNotOpen",
	FSError:             "kXR_FSError",
	InvalidRequest:      "kXR_InvalidRequest",
	IOError:             "kXR_IOError",
	NoMemory:            "kXR_NoMemory",
	NoSpace:             "kXR_NoSpace",
	NotAuthorized:       "kXR_NotAuthorized",
	NotFound:            "kXR_NotFound",
	InternalServerError: "kXR_ServerError",
	Unsupported:         "kXR_Unsupported",
	NoServer:            "kXR_noserver",
	NotFile:             "kXR_NotFile",
	IsDirectory:         "kXR_isDirectory",
	Cancelled:           "kXR_Cancelled",
	ItExists:            "kXR_ItExists",
	ChkSumErr:           "kXR_ChkSumErr",
	InProgress:          "kXR_inProgress",
	OverQuota:           "kXR_overQuota",
	SigVerErr:           "kXR_SigVerErr",
	DecryptErr:          "kXR_DecryptErr",
	Overloaded:          "kXR_Overloaded",
	FSReadOnly:          "kXR_fsReadOnly",
	BadPayload:          "kXR_BadPayload",
	AttrNotFound:        "kXR_AttrNotFound",
	TLSRequired:         "kXR_TLSRequired",
	NoReplicas:          "kXR_noReplicas",
	AuthFailed:          "kXR_AuthFailed",
	Impossible:          "kXR_Impossible",
	Conflict:            "kXR_Conflict",
	TooManyErrs:         "kXR_TooManyErrs",
}

// String returns the specification's name for the code, with its numeric value.
// A code this package does not know is rendered as its number alone: a server
// may be newer than this client, and an unrecognised code is still worth
// reporting exactly as it arrived.
func (code ServerErrorCode) String() string {
	if name, ok := serverErrorNames[code]; ok {
		return fmt.Sprintf("%s (%d)", name, int32(code))
	}
	return fmt.Sprintf("error %d", int32(code))
}

func (err ServerError) Error() string {
	return fmt.Sprintf("xrootd: %v: %s", err.Code, err.Message)
}

// Is reports whether the server's error means the same thing as one of the
// standard library's error values, so that a caller can write
//
//	errors.Is(err, fs.ErrNotExist)
//
// without knowing which transport, or which XRootD server version, produced
// the failure. The mapping is the same one the reference clients use.
func (err ServerError) Is(target error) bool {
	switch target {
	case fs.ErrNotExist:
		switch err.Code {
		case NotFound, NoServer, NoReplicas:
			// A manager answers kXR_noserver (and kXR_noReplicas) when nothing
			// it knows of holds the file. The file may exist somewhere the
			// cluster cannot see, but from the caller's side it is not there.
			return true
		}
	case fs.ErrExist:
		return err.Code == ItExists
	case fs.ErrPermission:
		switch err.Code {
		case NotAuthorized, AuthFailed, TLSRequired:
			// TLSRequired is a refusal to serve this caller as it connected,
			// which is the same decision as a denied authorization.
			return true
		}
	case fs.ErrInvalid:
		switch err.Code {
		case ArgInvalid, ArgMissing, ArgTooLong, InvalidRequest, FileNotOpen, BadPayload, Impossible:
			return true
		}
	}
	return false
}

// MarshalXrd implements Marshaler.
func (o ServerError) MarshalXrd(wBuffer *xrdenc.WBuffer) error {
	wBuffer.WriteI32(int32(o.Code))
	wBuffer.WriteBytes([]byte(o.Message))
	wBuffer.WriteBytes([]byte("\x00"))
	return nil
}

// UnmarshalXrd implements Unmarshaler.
func (o *ServerError) UnmarshalXrd(rBuffer *xrdenc.RBuffer) error {
	o.Code = ServerErrorCode(rBuffer.ReadI32())
	data := rBuffer.Bytes()
	if len(data) == 0 {
		return errors.New("xrootd: missing error message in server response")
	}
	o.Message = string(data[:len(data)-1])
	return rBuffer.Err()
}

// StreamID is the binary identifier associated with a request stream.
type StreamID [2]byte

// ResponseHeaderLength is the length of the ResponseHeader in bytes.
const ResponseHeaderLength = 2 + 2 + 4

// ResponseHeader is the header that precedes all responses (see xrootd protocol specification).
type ResponseHeader struct {
	StreamID   StreamID
	Status     ResponseStatus
	DataLength int32
}

// MarshalXrd implements xrdproto.Marshaler
func (o ResponseHeader) MarshalXrd(wBuffer *xrdenc.WBuffer) error {
	wBuffer.WriteBytes(o.StreamID[:])
	wBuffer.WriteU16(uint16(o.Status))
	wBuffer.WriteI32(o.DataLength)
	return nil
}

// UnmarshalXrd implements xrdproto.Unmarshaler
func (o *ResponseHeader) UnmarshalXrd(rBuffer *xrdenc.RBuffer) error {
	rBuffer.ReadBytes(o.StreamID[:])
	o.Status = ResponseStatus(rBuffer.ReadU16())
	o.DataLength = rBuffer.ReadI32()
	return rBuffer.Err()
}

// Error returns an error received from the server or nil if request hasn't failed.
func (hdr ResponseHeader) Error(data []byte) error {
	if hdr.Status != Error {
		return nil
	}
	if len(data) < 4 {
		return fmt.Errorf("xrootd: invalid ResponseHeader error: %w", io.ErrShortBuffer)
	}

	var serverError ServerError
	rBuffer := xrdenc.NewRBuffer(data)
	err := serverError.UnmarshalXrd(rBuffer)
	if err != nil {
		return fmt.Errorf("xrootd: error occurred during unmarshaling of a server error: %w", err)
	}

	return serverError
}

// RequestHeaderLength is the length of the RequestHeader in bytes.
const RequestHeaderLength = 2 + 2

// ResponseHeader is the header that precedes all requests (we are interested in StreamID and RequestID, actual request
// parameters are a part of specific request).
type RequestHeader struct {
	StreamID  StreamID
	RequestID uint16
}

// MarshalXrd implements Marshaler.
func (o RequestHeader) MarshalXrd(wBuffer *xrdenc.WBuffer) error {
	wBuffer.WriteBytes(o.StreamID[:])
	wBuffer.WriteU16(o.RequestID)
	return nil
}

// UnmarshalXrd implements Unmarshaler.
func (o *RequestHeader) UnmarshalXrd(rBuffer *xrdenc.RBuffer) error {
	rBuffer.ReadBytes(o.StreamID[:])
	o.RequestID = rBuffer.ReadU16()
	return rBuffer.Err()
}

// ServerType is the general server type kept for compatibility
// with 2.0 protocol version (see xrootd protocol specification v3.1.0, p. 5).
type ServerType int32

const (
	// LoadBalancingServer indicates whether this is a load-balancing server.
	LoadBalancingServer ServerType = iota
	// DataServer indicates whether this is a data server.
	DataServer
)

// FilepathRequest is a request that contains file paths.
// This interface is used to append opaque data to the request.
// Opaque data is received as part of the redirect response.
type FilepathRequest interface {
	Opaque() string          // Opaque returns opaque data from this request.
	SetOpaque(opaque string) // SetOpaque sets opaque data for this request.
}

// FilehandleRequest is a request that names an open file by the handle the
// server handed out when it was opened.
//
// A handle is meaningful only to the server that issued it, so such a request
// cannot simply be re-sent to a server it has been redirected to: the file has
// to be opened there first and the request pointed at the handle that server
// gives out. SetHandle is what does the pointing.
type FilehandleRequest interface {
	SetHandle(handle xrdfs.FileHandle)
}

// PathID is the socket identifier. It may be used in read and write requests to indicate
// which socket should be used for a response or as a source of data.
type PathID byte

// DataRequest is the request that operate over 2 sockets.
// One socket is used for sending the request and other is used to
// send or receive data.
type DataRequest interface {
	// PathID returns an identifier of the socket which should be used to read or write a data.
	PathID() PathID

	// SePathID sets the identifier of the socket which should be used to read or write a data.
	SetPathID(pathID PathID)

	// Direction returns the direction of the request: either reading or writing.
	Direction() DataRequestDirection

	// PathData returns the data which should be send to the data socket.
	PathData() []byte
}

// DataRequestDirection is the direction of the request: either reading or writing.
type DataRequestDirection int

const (
	// DataRequestRead indicates that request has reading direction.
	// In other words, the request obtains a data from the server.
	DataRequestRead DataRequestDirection = iota

	// DataRequestWrite indicates that request has writing direction.
	// In other words, the request sends a data to the server.
	DataRequestWrite
)

// RequestLevel is the security requirement that the associated request is to have.
type RequestLevel byte

const (
	SignNone   RequestLevel = 0 // SignNone indicates that the request need not to be signed.
	SignLikely RequestLevel = 1 // SignLikely indicates that the request must be signed if it modifies data.
	SignNeeded RequestLevel = 2 // SignNeeded indicates that the request mush be signed.
)

// SecurityLevel is the predefined security level that specifies which requests should be signed.
// See specification for details: http://xrootd.org/doc/dev45/XRdv310.pdf, p. 75.
type SecurityLevel byte

const (
	// NoneLevel indicates that no request needs to be signed.
	NoneLevel SecurityLevel = 0
	// Compatible indicates that only potentially destructive requests need to be signed.
	Compatible SecurityLevel = 1
	// Standard indicates that potentially destructive requests
	// as well as certain non-destructive requests need to be signed.
	Standard SecurityLevel = 2
	// Intense indicates that request that may reveal metadata or modify data need to be signed.
	Intense SecurityLevel = 3
	// Pedantic indicates that all requests need to be signed.
	Pedantic SecurityLevel = 4
)

// SecurityOverrideLength is the length of SecurityOverride in bytes.
const SecurityOverrideLength = 2

// SecurityOverride is an alteration needed to the specified predefined security level.
// It consists of the request index and the security requirement the associated request should have.
// Request index is calculated as:
//
//	(request code) - (request code of Auth request)
//
// according to xrootd protocol specification.
type SecurityOverride struct {
	RequestIndex byte
	RequestLevel RequestLevel
}

// MarshalXrd implements xrdproto.Marshaler
func (o SecurityOverride) MarshalXrd(enc *xrdenc.WBuffer) error {
	enc.WriteU8(o.RequestIndex)
	enc.WriteU8(byte(o.RequestLevel))
	return nil
}

// UnmarshalXrd implements xrdproto.Unmarshaler
func (o *SecurityOverride) UnmarshalXrd(dec *xrdenc.RBuffer) error {
	o.RequestIndex = dec.ReadU8()
	o.RequestLevel = RequestLevel(dec.ReadU8())
	return dec.Err()
}

// SetOpaque sets opaque data part in the provided path.
func SetOpaque(path *string, opaque string) {
	pos := strings.LastIndex(*path, "?")
	if pos != -1 {
		*path = (*path)[:pos]
	}
	*path = *path + "?" + opaque
}

// Opaque returns opaque data from provided path.
// A path that carries no "?" carries no opaque data, and Opaque returns "".
func Opaque(path string) string {
	pos := strings.LastIndex(path, "?")
	if pos == -1 {
		return ""
	}
	return path[pos+1:]
}

// SplitPath splits a path field into the file name and the opaque data (CGI)
// that travels with it. The split is at the first "?", which is where a server
// splits: everything past it is handed to the authorization layer unparsed, so
// a "?" inside a token value belongs to the token rather than opening a further
// field.
//
// This is not the same split as Opaque and SetOpaque, which read and replace
// the last "?"-delimited field of a path — the convention the redirect handling
// works to.
func SplitPath(p string) (name, opaque string) {
	name, opaque, _ = strings.Cut(p, "?")
	return name, opaque
}

// JoinPath returns the child of dir named name, carrying over the opaque data
// dir travels with.
//
// A client that walks a remote tree builds the name of a child from the name of
// its parent, and joining onto a path that carries opaque data yields
// "/dir?authz=t/child": a name no server holds, addressed with a token no
// server can parse. Every level of a walk has to be authorized on its own, so
// the opaque data is carried to the child rather than left behind.
func JoinPath(dir, name string) string {
	d, opaque := SplitPath(dir)
	p := path.Join(d, name)
	if opaque == "" {
		return p
	}
	return p + "?" + opaque
}

// ReadRequest reads a XRootD request from r.
// ReadRequest returns entire payload of the request including header.
// ReadRequest requires serialization since multiple ReadFull calls are made.
func ReadRequest(r io.Reader) ([]byte, error) {
	// 16 is for the request options and 4 is for the data length
	const requestSize = RequestHeaderLength + 16 + 4
	request := make([]byte, requestSize)
	if _, err := io.ReadFull(r, request); err != nil {
		return nil, err
	}

	dataLength := binary.BigEndian.Uint32(request[RequestHeaderLength+16:])
	if dataLength == 0 {
		return request, nil
	}

	data := make([]byte, dataLength)
	if _, err := io.ReadFull(r, data); err != nil {
		return nil, err
	}

	return append(request, data...), nil
}

// WriteResponse writes a XRootD response resp to the w.
// The response is directed to the stream with id equal to the streamID.
// The status is sent as part of response header.
// WriteResponse writes all data to the w as single Write call, so no
// serialization is required.
func WriteResponse(w io.Writer, streamID StreamID, status ResponseStatus, resp Marshaler) error {
	var respWBuffer xrdenc.WBuffer
	if resp != nil {
		if err := resp.MarshalXrd(&respWBuffer); err != nil {
			return err
		}
	}

	header := ResponseHeader{
		StreamID:   streamID,
		Status:     status,
		DataLength: int32(len(respWBuffer.Bytes())),
	}

	var headerWBuffer xrdenc.WBuffer
	if err := header.MarshalXrd(&headerWBuffer); err != nil {
		return err
	}

	response := append(headerWBuffer.Bytes(), respWBuffer.Bytes()...)
	if _, err := w.Write(response); err != nil {
		return err
	}
	return nil
}

// ReadResponse reads a XRootD response from r.
// ReadResponse returns the response header and the response body.
// ReadResponse requires serialization since multiple ReadFull calls are made.
func ReadResponse(r io.Reader) (ResponseHeader, []byte, error) {
	var header ResponseHeader
	data, err := ReadResponseWithReuse(r, make([]byte, ResponseHeaderLength), &header)
	return header, data, err
}

// ReadResponseWithReuse reads a XRootD response from r. A response header is read into headerBytes and
// unmarshaled to header for the reusing reasons.
// ReadResponseWithReuse returns the response body.
// ReadResponseWithReuse requires serialization since multiple ReadFull calls are made.
func ReadResponseWithReuse(r io.Reader, headerBytes []byte, header *ResponseHeader) ([]byte, error) {
	if _, err := io.ReadFull(r, headerBytes); err != nil {
		return nil, err
	}
	rBuffer := xrdenc.NewRBuffer(headerBytes)
	if err := header.UnmarshalXrd(rBuffer); err != nil {
		return nil, err
	}
	if header.DataLength == 0 {
		return nil, nil
	}
	if header.DataLength < 0 {
		return nil, fmt.Errorf("xrootd: response announces a negative data length (%d)", header.DataLength)
	}
	if header.DataLength > MaxResponseLength {
		return nil, fmt.Errorf("xrootd: response body of %d bytes exceeds the %d-byte limit", header.DataLength, MaxResponseLength)
	}
	var data = make([]byte, header.DataLength)
	if _, err := io.ReadFull(r, data); err != nil {
		return nil, err
	}
	return data, nil
}
